### ISSUE TITLE
Integrate Log In interface

### ISSUE THREAD

**Issue by bitsky-team** [bitsky-team/bitsky#2]
The interface should be divided into **two parts**:
  - left part: log in form with "remember me" checkbox
  - right part: 3 tabs (blog, docs, support)

### Tasks
- Front-End
  - [x] Left part
  - [ ] Right part
  - [x] Comments
  - [x] Unit tests
- Back-End
  - [x] JWT token-based authentication
  - [x] isAuthenticated middleware
  - [x] Unique email address
  - [x] Comments
  - [x] Unit tests

**Comment by jasonvanmalder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implements Log In interface](https://trello.com/c/tjdr4vte/1-implements-log-in-interface)

**Comment by jvnm-dev** [comment]
Note: the right part will be the subject of another issue.
